### ISSUE TITLE
FR: auto-request review after a short delay

### ISSUE THREAD

**Issue by iamdanfox** [palantir/policy-bot#128]
## What happened?

I've seen a couple of instances already where:

1. someone opens a PR, 
2. then as soon as it's opened tries to request a specific reviewer, 
3. policy-bot also races to assign reviewers (and usually wins)

This results in more people being notified than necessary, and one of my goals with the auto request reviews thing is to try and reduce notifications to exactly those necessary to get stuff done and no more.

## What did you want to happen?

My proposal is to introduce a short delay to accommodate human forgetfulness, so that if people create a PR and then immediately assign a reviewer, policy-bot won't touch the PR.

**Comment by asvoboda** [comment]
I believe this should be entirely fixed by #126 , since policy-bot will check a second time if reviewers were requested just before assigning them. Previously we were a little bit naive and only checked once, performed calculations, and then requested reviewers without checking if a human added anyone.

**Comment by iamdanfox** [comment]
But if users see their created PR and then 5 seconds later try to request a review, policy-bot probably will have got there first right? My proposal would be to introduce maybe a 20second delay?

**Comment by asvoboda** [comment]
The race condition should be covered, since policy-bot will check _right_ before requesting reviewers. Lets let this bake for a while and see if we actually want a delay in practice.
