### ISSUE TITLE
[Enhancement] Support no_changed_files predicate

### ISSUE THREAD

**Issue by henryptung** [palantir/policy-bot#140]
Currently, the `only_changed_files` predicate fails if no files are actually changed. Should support `or(only_changed_files, no_changed_files)` to model `(changed files) SUBSET (restricted set)`.

**Comment by bluekeyes** [comment]
A `no_changed_files` predicate was added in #756, although I'm not sure if it fully satisfies the original request here. If there's still something missing, we can re-open this.
