### ISSUE TITLE
An error evaluating a rule in a disjunction should not cause an error in the policy

### ISSUE THREAD

**Issue by ferozco** [palantir/policy-bot#147]
Currently, rules that apply to specific paths will error if more than 300 files are modified in a single PR which causes the entire policy evaluation to error. 

I'd suggest that if an erroring rule is part of a disjunction then the policy should return the result of evaluating the policy "ignoring" the failing rule

**Comment by bluekeyes** [comment]
This is the current behavior for `or` conditions, but `and` conditions (including the implicit top-level `and`) will propagate errors. I think the real fix will be to remove the 300 file limit (#11).
