### ISSUE TITLE
Assign reviewers when predicate rules change

### ISSUE THREAD

**Issue by bluekeyes** [palantir/policy-bot#153]
Recent predicate additions (`has_labels`, `has_successful_status`) can enable rules well after a PR has opened in response to outside events. When these rules are enabled, we should re-run reviewer assignment to assign reviewers for these new rules, if enabled.

**Comment by bluekeyes** [comment]
This same issue applies when additional commits to the PR modify files that trigger new review assignment rules. This is complicated by the fact that we may have already assigned reviewers based on the original files.

Maybe instead of ignoring PRs with any reviewers, we should ignore PRs with any reviewers that were added by something other than Policy Bot?

**Comment by Mazon** [comment]
Any progress on this one? We use this exact user case where people create PR and forget or don't have all information to add all labels.

**Comment by bluekeyes** [comment]
I started working on this today, but don't have an estimate yet for when it will be complete.

**Comment by Mazon** [comment]
Awesome! Will test it out. Thank you 👍

**Comment by bluekeyes** [comment]
Note that this hasn't made it into a release yet, so you'll have to test with the `snapshot` Docker image or by building from source.
