### ISSUE TITLE
Allow regex matching for comment based approval

### ISSUE THREAD

**Issue by Coffee-Boyy** [palantir/policy-bot#155]
Hi, I am looking to have comments approve a PR but be able to setup a rule that matches on a regular expression of the comment rather than whether the comment just contains the string.

For example, I'd like my comment to be able to say "This has been manually tested with build 1.0.12" and have the policy validate against "This has been (manually)? tested with build [1.0.\d+].*"

**Comment by bluekeyes** [comment]
This makes sense to me. In retrospect, the `comments` property probably should have been an exact, full comment match and then a second `comment_patterns` property accepts regular expressions and also works for substring matches.

I'll look at adding the `comment_patterns` property to support this.
