### ISSUE TITLE
[Question] Operate behind AWS ELB

### ISSUE THREAD

**Issue by jurijzahn8019** [palantir/policy-bot#163]
Hi, i have troubles to run docker container behind AWS ELB.

OAuth requests use wrong redirect_url which is always http://localhost:8080

in config file i have: 

```yaml
server:
  public_url: https://mydomain.foo.bar/
```

Tried set `logging.level`  to  `debug` did not delivered any info.

What am i missing?

Many thanks in advance.

**Comment by bluekeyes** [comment]
The OAuth redirect URL is set using the [value of the `Host` header](https://github.com/palantir/go-githubapp/blob/develop/oauth2/handler.go#L180-L196) of the request that starts the authentication flow. Is it possible that there's a reverse proxy (like NGINX or Apache) between the ELB and the Docker container that is removing or setting a new value for the `Host` header? In my experience, ELBs don't modify this header.

**Comment by jurijzahn8019** [comment]
Thank You for answering! :) I will check.

**Comment by jurijzahn8019** [comment]
Thank you very much! You are right. There is an apache in between. I gave a hint to our specialist, so we will fix it.
