### ISSUE TITLE
request_review: mode: team

### ISSUE THREAD

**Issue by NargiT** [palantir/policy-bot#166]
I would love to see a mode in which request_review would affect a team instead of users of a team.

In my use case our teams are ldap based (running github entreprise on perm) and we have managers in our teams. We do not want create new teams with only tech people because we have to maintain them.

Affecting a group instead of users is also more future proof as is allow new comers to see existing issues. 

How do you think we could leverage this ?

**Comment by asvoboda** [comment]
Hey @NargiT ,

Thanks for the request. We've talked about doing this internally, and while it makes sense we just haven't yet had the time to implement the feature.

**Comment by NargiT** [comment]
from your experience is the feature hard to implement ? I never wrote golang before so I need to know how "big" the feature might be before to help contributing.

**Comment by AdamDeHovitz** [comment]
This has been implemented and can now be closed
