### ISSUE TITLE
disable healthcheck log entry to reduce noise in the logs

### ISSUE THREAD

**Issue by huydinhle** [palantir/policy-bot#172]
Can we have a flag to disable this line in the logs to reduce noise in policy-bot logs?
```
2020-03-11T18:28:24.395901944Z |INFO| http_request elapsed=0.238318 method=GET path=/ rid=bpkiri3g83ahlvath4k0 size=1986 status=200```

**Comment by bluekeyes** [comment]
I think this is a reasonable request, but I'm not quite sure how to implement it. This message is part of the standard request logging provided by [go-baseapp](https://github.com/palantir/go-baseapp), so it's unclear to me if we should modify that library to have some kind of filtering or if we should override the logging function here in `policy-bot`.

Note that if we do implement this, it would be for the `/api/health` endpoint, which is what I recommend using for health checks. That endpoint is also slightly easier to filter out with `grep` or another tool than the plain `/` path.
