### ISSUE TITLE
server/templates no such file or directory

### ISSUE THREAD

**Issue by M-Bohram** [palantir/policy-bot#197]
Hello,
After I have configured policy-bot.yml (in config directory) with my github app (app ID..etc) and used the command:
docker run --rm -v "$(pwd)/config:/secrets/" -p 8080:8080 palantirtechnologies/policy-bot:latest
I got the error shown below:
![image](https://user-images.githubusercontent.com/21022569/85707208-4209ee80-b6e3-11ea-99a5-1086c78f97a1.png)

**Comment by bluekeyes** [comment]
Hi @M-Bohram, sorry you hit this issue. Can you remove `files` section from the configuration file and try again? 

It seems our example configuration file contains the paths for local development, not the paths used in the Docker container. The server will use correct default values when this section is missing from the configuration.

I'll also put up a PR to fix the configuration file so it works with the Docker container and distributions by default.

**Comment by M-Bohram** [comment]
Thanks @bluekeyes for your reply, but unfortunately still not working :(

**Comment by bluekeyes** [comment]
Can you share the configuration you are using (with any sensitive fields, like the private key, removed)? Is the error the same as the one in your screenshot from earlier?

**Comment by M-Bohram** [comment]
okay, here is the configuration file with sensitive fields replaced with "####":

server:
  address: "0.0.0.0"
  port: 8080

logging:
  text: true
  level: debug

github:
  web_url: "https://github.########.com"
  v3_api_url: "https://github.#########.com/api/v3"
  app:
    integration_id: 32
    webhook_secret: "development"
    private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      ###########################
      -----END RSA PRIVATE KEY-----
  oauth:
    client_id: "####################"
    client_secret: "########################"

sessions:
  key: "secretsessionkey"

options:
  policy_path: .policy.yml
  status_check_context: policy-bot
  app_name: coreapp-policy

But the error still the same, server/template: no such a file or directory
