### ISSUE TITLE
Unsupported Protocol Scheme

### ISSUE THREAD

**Issue by MayarSahab** [palantir/policy-bot#201]
Hi,

- I am currently having an issue with the app as it is now configured on the github and should be working but actually it is not. The app webhook seems to be working and there are payloads received without any error but when I try to raise a PR to  the target repo I can't see the Policy check even I have configured ".policy.yml".
- When I check the logs of the Bot I can see an error "Unsupported protocol scheme" not sure what's the cause of it. I have attached the configuration file of the bot (removed the sensitive data) and a screenshot of the errors popping [up.](url)
[policy-bot-yaml .txt](https://github.com/palantir/policy-bot/files/4865553/policy-bot-yaml.txt)

<img width="937" alt="error1" src="https://user-images.githubusercontent.com/18345201/86353241-3bd9bc00-bc67-11ea-9223-bd972ebaa3d5.png">
<img width="790" alt="error2" src="https://user-images.githubusercontent.com/18345201/86353246-3da37f80-bc67-11ea-8c89-a2ea9b7e167b.png">

**Comment by bluekeyes** [comment]
Thank you for sharing the configuration file. I believe this error is because the `v4_api_url` option is commented out. Policy Bot uses both the v3 (REST) and v4 (GraphQL) APIs, so both URLs must be set. Try setting that option to the correct value for your GitHub instance and see if it resolves the issue.

**Comment by MayarSahab** [comment]
@bluekeyes : Thanks for your response. However, unfortunately I have configured the GraphQl  API and the error still persists.

-On a side note I am deploying the app on kubernetes pod using the docker image. Here's a screenshot of the docker file I  am using as well.

-I have attached the updated config file as well.
<img width="390" alt="Dockerfile-1" src="https://user-images.githubusercontent.com/18345201/86383393-6723d180-bc8e-11ea-8a88-81598850e567.PNG">

**Comment by bluekeyes** [comment]
To clarify, which of the two errors are you still seeing? If you are still seeing the `422 Validation Failed` error, try also setting the value of `public_url` to the correct public URL of your server. I realize now that the comment on this field in the sample configuration wrongly implies it is only needed in certain situations. In reality, Policy Bot always uses this value when posting status checks for pull requests.

**Comment by MayarSahab** [comment]
Yes, the error is 422 Validation error.
-What do you mean by the public URL of the server as the app is not installed on a server, it is installed on a pod. Do you mean to put the Public URL of the bot configured on github? or the IP of our virtual machine on which our k8s cluster is hosted?

**Comment by bluekeyes** [comment]
The `public_url` property should be the same as the URL where GitHub sends webhooks (but without the `/api/github/hook` path). This is also the URL where users go to view the Policy Bot UI.

**Comment by MayarSahab** [comment]
We have actually two URLs:

Public Link (Bot UI) : https://github.xxxxxxxxx.com/github-apps/coreapp-policy
Webhook URL: https://probot-policy-xxxgs.xxxxxxxx.xxxxxx.com/api/github/hook
Which one should be setup?

**Comment by bluekeyes** [comment]
It should be the second one: `public_url: https://probot-policy-xxxgs.xxxxxxxx.xxxxxx.com/`

**Comment by MayarSahab** [comment]
@bluekeyes : Thanks alot for your help, it worked after changing the public URL as mentioned.
