### ISSUE TITLE
Configure maximum depth

### ISSUE THREAD

**Issue by AdamDeHovitz** [palantir/policy-bot#219]
Currently policy-bot has a maximum recursive depth of 5 for conjunctions, which our use case has recently superseded. Instead of hard coding it, can the max depth be configurable?

**Comment by bluekeyes** [comment]
Closing this as a duplicate of #168. I don't really want to make this configurable yet, but I think doubling the limit is fine (the original value was arbitrary). I'll include that in the next release.
