### ISSUE TITLE
Focused policy-bot details view

### ISSUE THREAD

**Issue by AdamDeHovitz** [palantir/policy-bot#224]
The current policy-bot details view is enormously helpful, but as our policy has grown more complicated it's become harder and harder to focus passed skipped/approved subtrees to find the policies that actually need approval. 

What would be great is a toggle that enables a focused view that highlights pending subtrees needed to satisfy the policy. I'd be happy to share an internal example of where this would be especially useful, or make a contribution at a later date.

**Comment by bluekeyes** [comment]
This sounds like a good enhancement that I don't think will be difficult to implement. I'll see if I have time to try it in the next week or two.
