### ISSUE TITLE
question: install a pvt all with self hosting, install error

### ISSUE THREAD

**Issue by anirban1c** [palantir/policy-bot#237]
getting stumped on a app install getting "GET","path":"/api/github/"  -- status":404,"

{"level":"info","rid":"bu2qckjssoseprbujr0g","method":"GET","path":"/api/github/","client_ip":"172.17.0.1:54460","status":404,"size":19,"elapsed":0.0285,"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36","time":"2020-10-13T13:06:26.471849700Z","message":"http_request"}

created a GitHub app
policy-bot.yaml has the secret and token 
install it on a pvt GitHub

**Comment by bluekeyes** [comment]
Policy Bot has two handlers under the `/api/github/...` path:

- `/api/github/hook` - the target for webhooks delivered by GitHub
- `/api/github/auth` - the OAuth2 redirect URL

Can you verify that both the "Webhook URL" and the "User authorization callback URL" have the correct paths in the GitHub App configuration in GitHub?

**Comment by anirban1c** [comment]
web hook url : http://86.177.240.146/api/github/hook
user authorisation call back url: http://86.177.240.146/api/github/auth 

it the same as the  the OAuth2 redirect URL ? or do I have to create a oauth app as well ? 
what I was trying to figure out from the code

**Comment by anirban1c** [comment]
or how this oath app field is used: Authorization callback URL 

which is set to the same http://86.177.240.146/api/github/auth

**Comment by anirban1c** [comment]
curl with the githuibapp PEM gets me a 200 as well

stumped by this issue otherwise this is a really useful bit of feature we need badly since moving off bitbucket :)

b.com/app
HTTP/1.1 200 OK
Date: Tue, 13 Oct 2020 16:54:50 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1943
Server: GitHub.com
Status: 200 OK


{
  "id": 84497,
  "slug": "policy-bot1",
  "node_id": "MDM6QXBwODQ0OTc=",
  "owner": {
    "login": "ao-cdt-automation-01",
    "id": 71750299,
    "node_id": "MDQ6VXNlcjcxNzUwMjk5",
    "avatar_url": "https://avatars1.githubusercontent.com/u/71750299?v=4",
    "gravatar_id": "",

**Comment by bluekeyes** [comment]
Is it possible that you set the "Setup URL (optional)" field to `http://86.177.240.146/api/github/`? That field should usually be blank:

<img width="400" alt="setup-url" src="https://user-images.githubusercontent.com/1745813/95894215-9e018d00-0d3d-11eb-8a31-7e560a3978b0.png">

Otherwise, I'm afraid I'm not sure what steps lead to the error you reported. Can you explain what you did to get the 404 error?

**Comment by anirban1c** [comment]
setup url is blank, 
checked - Request user authorization (OAuth) during installation 

install app, from the same which created the GitHub app 
brings up the install & authorise page, cick that button 
gets the error 404 page not found

(docker container running on my laptop, where I have my public IP port forwarding it to 8080)
in the docker container logs


(base) anirban@Nothing-To-Look-Here policy-bot % docker run --rm -v "$(pwd)/config:/secrets/" -p 8080:8080 palantirtechnologies/policy-bot:latest
{"level":"info","time":"2020-10-13T17:24:32.938841800Z","message":"Server listening on 0.0.0.0:8080"}
{"level":"info","rid":"bu2u61bssos5kcpb2lkg","github_event_type":"installation","github_delivery_id":"146fb080-0d79-11eb-9df9-5980db2843f6","time":"2020-10-13T17:25:25.602033500Z","message":"Received webhook event"}
{"level":"info","rid":"bu2u61bssos5kcpb2lkg","method":"POST","path":"/api/github/hook","client_ip":"172.17.0.1:55200","status":202,"size":0,"elapsed":0.3875,"user_agent":"GitHub-Hookshot/4ca69d5","time":"2020-10-13T17:25:25.602250100Z","message":"http_request"}
{"level":"info","rid":"bu2u61bssos5kcpb2lk0","method":"GET","path":"/api/github/auth?code=f41b83f1b99616a02897&installation_id=12374164&setup_action=install","client_ip":"172.17.0.1:55196","status":302,"size":35,"elapsed":615.1589,"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36","time":"2020-10-13T17:25:26.165771900Z","message":"http_request"}
{"level":"info","rid":"bu2u61jssos5kcpb2ll0","method":"GET","path":"/api/github/","client_ip":"172.17.0.1:55196","status":404,"size":19,"elapsed":0.02,"user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36","time":"2020-10-13T17:25:26.173368700Z","message":"http_request"}

**Comment by anirban1c** [comment]
it does say in the install page 
Next: you'll be redirected to http://86.177.240.146/api/github/auth

**Comment by anirban1c** [comment]
where is this getting redirected 
"GET","path":"/api/github/auth?code=68edd65a  - 302

"GET","path":"/api/github/"

**Comment by anirban1c** [comment]
or if there is anyway I could use the web hook configured per repo without installing it as an app, could be my permissions on the organisation for the pvt repos

**Comment by bluekeyes** [comment]
> checked - Request user authorization (OAuth) during installation

Try unchecking this option. OAuth authentication is not required as part of installation (it's only used when viewing the details page for a pull request) and I believe this exposes a bug in Policy Bot.

If you attempt to login without visiting a page first, the redirect property of the session is not set. When [the login handler](https://github.com/palantir/policy-bot/blob/develop/server/handler/login.go#L61) redirects to this empty string, the browser goes up one level to `/api/github/` instead of going to `/` as intended. I'll fix this in the server tomorrow, but disabling the "Request user authorization during installation" option should also resolve your problem.

**Comment by anirban1c** [comment]
thanks bluekeyes, I did end up doing that last night

also ended up deploying it on a azure  vm with a proper lets encrypt ssl cert, just in case the http urls where causing this, 

thanks for your prompt response
