### ISSUE TITLE
Dismiss stale approvals if invalidate_on_push: true

### ISSUE THREAD

**Issue by AdamDeHovitz** [palantir/policy-bot#239]
One feature natively support by github pull-request reviews is dismissing stale approvals:
![image](https://user-images.githubusercontent.com/5420178/96142228-dfc23d00-0ecf-11eb-9d6a-a005ec796224.png)

I believe the `invalidate_on_push` option should similarly dismiss stale approvals to help clear the UI and also enable the rerequesting of reviewers by policy-bot's request_reviewers functionality.

**Comment by KnisterPeter** [comment]
@bluekeyes Not sure whom to tag here, so I've choosen you. :smiley: 
Are you up for a contribution here?

**Comment by KnisterPeter** [comment]
Also I think this is kind of related: https://github.com/palantir/policy-bot/commit/5e81dd9f65ca341104d917482739c1e38e2b0ba6
The main issue we currently have with this is:

- We have a PR
- A few approvals are done through github reviews
- Policy-Bot is configured to dismiss stale reviews
- A new commit is pushed

Then the github approvals are still there and not invalidated/dismissed.
Using the github option to dismiss all of them is possible, but in our case a few teams would like to keep their existing approvals and a few won't. This isn't possible with github, but policy-bot could handle this case.

**Comment by aw185176** [comment]
Also hitting the same snag point onboarding engineers who are used to the GH UI being the up-to-date source of truth for state of a PR, if pointed in the right direction I may have cycles to put together a patch.
