### ISSUE TITLE
feature request: Check on the PR title

### ISSUE THREAD

**Issue by NotSoImportant** [palantir/policy-bot#244]
Have an approval and denial rule that checks the PR title against a regex.

Like this you can enforce only PRs with valid commit messages can be merged (e.g. https://www.conventionalcommits.org/en/v1.0.0/#summary)

Github hooks already trigger on renaming a PR.

**Comment by gberger** [comment]
+1 this would help in avoiding contributors leaving the default PR title "Update filename.txt"

**Comment by NotSoImportant** [comment]
Thank you :-)
Is this included in [latest version 1.21.0](https://hub.docker.com/layers/palantirtechnologies/policy-bot/1.21.0/images/sha256-3d2b2b70ba2873a4dbd9a04f50049dbfe5f784078bdbdafab01de2bef3c41813?context=explore)?
I cannot find release notes.

**Comment by asvoboda** [comment]
Hey @NotSoImportant,

The changelog/release notes are listed in the Github release: https://github.com/palantir/policy-bot/releases/tag/v1.21.0
