### ISSUE TITLE
[FR] Add links to GHE teams for rules

### ISSUE THREAD

**Issue by buffer51** [palantir/policy-bot#247]
A common workflow is that users seeking a PR approved will review the policy-bot CI check to see what rules are blocking. They would like to be able to identify who can approve the rule, but most users will not bother / know how to check the `policy.yml` to get the answer. On top of that, if the rules is tied to a GHE team, the user has then to find the team in GHE to see who is in it.

Ideally we handle users, organizations & teams, but I think teams is the most common one and therefore higher value for a v0.

**Comment by bluekeyes** [comment]
This is similar to #49, but might be easier to implement, since it doesn't risk exposing private team details or finding a way to format teams and organizations with many members.

**Comment by buffer51** [comment]
Ah cheers for the related issue, I felt there must have been one but couldn't find it. I'll fold the proposal into that issue.
