### ISSUE TITLE
Handle review dismissal event

### ISSUE THREAD

**Issue by ungureanuvladvictor** [palantir/policy-bot#28]
If a GH review is performed with the result of request changes policybot will correctly fail the status check. If a person dismisses that review policybot will not reset the status check to pending.

**Comment by bluekeyes** [comment]
I haven't tried reproducing this, but while we handle the webhook event for this we don't handle the `review_dismissed` event in the pull request timeline. This means we probably only see the original review (and later approvals), and don't process the fact that the earlier review was removed.

I'm refactoring the related code for another issue, so I'll try to fix this while I'm there.
