### ISSUE TITLE
Allow approval based on source branch name

### ISSUE THREAD

**Issue by styu** [palantir/policy-bot#32]
For example,

```
if:
  with_source_branch:
    pattern: "^(regexPattern)$"
```

This would be useful for PRs automatically opened/frequently opened on the same branch, e.g. to update dependencies

**Comment by bluekeyes** [comment]
Is it difficult to achieve the same result using file patterns? A `with_source_branch` option seems insecure unless combined with other predicates, since a person could theoretically change anything they wanted on a branch used for something else by convention.

**Comment by styu** [comment]
We actually achieved this workflow a different way - bulldozer's "merge when ready" labels are now only applied under certain conditions (e.g. tags for auto-generated PRs), so I don't think this is necessary for the workflow I was thinking of anymore
