### ISSUE TITLE
Don't allow multiple approvals by the same person

### ISSUE THREAD

**Issue by Dgleish** [palantir/policy-bot#33]
We recently enabled a co-contributor approval option, where you allowed approvals from contributors, but required two approvals. The behaviour of this however was to allow the same person to approve twice (eg if they had at least two comments with a 👍 ). I don't think this is desirable behaviour - one person's approval should only ever count once.

**Comment by bluekeyes** [comment]
Thanks for reporting this, I agree that this behavior is incorrect. We just ran into this for another set of internal projects as well, so I'll try to get a fix out in the next day or two.
