### ISSUE TITLE
Env Var for Public URL

### ISSUE THREAD

**Issue by james-soak** [palantir/policy-bot#355]
Hello,

Thanks for creating a great tool, I've set it up for our team this morning using Digital Ocean's app platform and the docker image however I cannot access the 'View Details' link from the GitHub UI as the links default to `localhost:8080`. The configuration file allows this to be changed but not via environment variables from what I can see.

It would be really useful to be able to have this set without needing to create a config file and wrap it up in a custom docker image just for a single value. I'd happily put a PR in to do this rather than make a request like this, unfortunately I'm unfamiliar with the Go language.

Many thanks.

**Comment by asvoboda** [comment]
Hey @james-soak ,

I believe you should be able to set this via env vars. Specifically, try setting `POLICYBOT_PUBLIC_URL`. Sounds like we should also follow up here to make the documentation a bit better.

[1] https://github.com/palantir/go-baseapp/blob/develop/baseapp/config.go#L45
[2] https://github.com/palantir/policy-bot/blob/develop/server/config.go#L69

**Comment by james-soak** [comment]
@asvoboda ah perfect! Thank you so much. That has indeed worked 👍

**Comment by asvoboda** [comment]
Glad to hear it.
