### ISSUE TITLE
Support Env Variables for Options in Server Config

### ISSUE THREAD

**Issue by devinburnette** [palantir/policy-bot#363]
Hello again!

We're looking at setting up a shared repository that isn't the default .github repository. I see the option for it in the server config to change where policy bot looks for a shared policy config, but I don't see that as being a currently supported Env variable. We could probably just as easy deploy a config file with this in it, but so far this is the only thing and Env variables are a lot easier for us to manage.

Would you accept a PR to make the server config parser set options from Env before filling the defaults?

**Comment by bluekeyes** [comment]
Sure, we [already do this for some values](https://github.com/palantir/policy-bot/blob/develop/server/config.go#L69-L74) (the HTTP server options, GitHub configuration, and secrets), but have been pretty haphazard about adding environment variable support for other options. If you'd like to take a pass at adding in missing ones, that would definitely be appreciated, but I'm also happy to accept a PR that just adds the one variable you need right now.
