### ISSUE TITLE
Approval Question for branch protection

### ISSUE THREAD

**Issue by shresthaujjwal** [palantir/policy-bot#366]
We have repos that is configured with branch protection to require atleast 2 review and approval. is it possible to use policy-bot to do automatic approval. 

Since we need 2 approval do we need 2 policy bot ? 

![image](https://user-images.githubusercontent.com/16170098/149588274-fc1f42e0-4c4d-4ec6-9663-bf41de6255c7.png)

**Comment by bluekeyes** [comment]
Hey @shresthaujjwal,

Policy Bot does not currently post pull request reviews on PRs, so it can never satisfy the review requirement (see #162.) Instead, it posts a status check that effectively _replaces_ the "required reviews" part of branch protection. The way we recommend using Policy Bot is to:

1. Disable "required reviews" on your protected branches
2. Enable required status checks and require the `policy-bot: master` check
3. Add a `.policy.yml` file to your repository that requires 2 approvals (or whatever other conditions you'd like.) Use the `invalidate_on_push` option to mimic the "Dismiss stale pull request approvals" setting in GitHub.

Hopefully that answers your question, but let me know if anything is still unclear.

**Comment by shresthaujjwal** [comment]
Thanks @bluekeyes for quick response. Can bulldozer bot satisfy my requirement. I am trying to achieve same requirements as #162

**Comment by bluekeyes** [comment]
I don't think so. Bulldozer will merge pull requests that meet all other required conditions, but will not post reviews. As I mentioned, in our own workflow we do not use GitHub's required review feature and instead use a required status check and Policy Bot to implement our review enforcement. I'm afraid you may have to look elsewhere for now if you need something that works with GitHub's required reviews.

**Comment by shresthaujjwal** [comment]
Thanks @bluekeyes for clarification. So if I switch to policy-bot. Will it automatically make the policy-bot: master status check required automatically?
I have lots of repo in my enterprise it's not possible to ask everyone to manually make that change. Please advise.

**Comment by bluekeyes** [comment]
No, Policy Bot will not change repository settings. Note that in addition to making the Policy Bot check required, you would also have to add a `.policy.yml` file to each repository or add a default policy to the `.github` repository in each organization.

If you have a user with admin access to all the organizations or repositories in your enterprise, it should be relatively straightforward to change branch protections using [the REST API](https://docs.github.com/en/rest/reference/branches#protected-branches). You could also look at using something like [probot/settings](https://github.com/probot/settings) to manage repository settings with code.

**Comment by shresthaujjwal** [comment]
Thank you @bluekeyes `probot\settings` looks very promising. thank you again
