### ISSUE TITLE
FR: UI should give links to Github users and teams that can approve specific checks

### ISSUE THREAD

**Issue by aldexis** [palantir/policy-bot#368]
I believe this may be pretty related to https://github.com/palantir/policy-bot/issues/49, but also slightly different (or expands further on it)

## What happened
It is a very common workflow to make a PR and see the policy bot check stuck at yellow. Clicking on the check to see the details is the next natural step for it.

Unfortunately, it is hard to figure out who may be the correct team or user to reach out to right now:
- It is defined in the repo's policy config file
- That config file may refer to a remote one in another repo, which we need to pull up
- The config file may then reference a github team from another org, which I need to go and find the members of

## What should have happened

The other issue I linked proposed to list the users and teams from the config in the UI, but I'd like to go one step further and make direct links to github users and teams.

This makes it trivial to see who to ping for questions/reviews, by following the links. If a team is private (e.g. I'm not a member of the org), that's fine too. I then know the name of the team, which is the best I can hope for, without the app leaking the membership contents in the UI directly.

**Comment by bluekeyes** [comment]
Added in #407.
