### ISSUE TITLE
The order of expected and actual in tests are wrong

### ISSUE THREAD

**Issue by yiweny** [palantir/policy-bot#410]
The actual testing object should go first in the order. 
I think it's wrong in some of the tests: https://github.com/palantir/policy-bot/blob/develop/policy/predicate/author_test.go#L458
Testify package documentation here: https://pkg.go.dev/github.com/stretchr/testify/assert

This is annoying when I am debugging. I will fix in a separate PR after finishing my current PR.

**Comment by bluekeyes** [comment]
While I'm sure we have some tests that switch these around, the example you linked appears correct to me:

```go
assert.Equal(t, tc.Expected, ok, "predicate was not correct")
```

```go
func Equal(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool
```

Have you found other places where the values are switched?
