### ISSUE TITLE
Permission failure for private repos

### ISSUE THREAD

**Issue by asvoboda** [palantir/policy-bot#42]
In 1.4.0 we started using the timeline API, which seems to have some slightly unexpected permission changes for private repos. The result is that policy-bot is unable to evaluate policy ymls for private repos.

Error in the UI:
```
failed to compute approval status: failed to get approval candidates: failed to fetch comments: failed to list pull request timeline: Resource not accessible by integration
```

I think the fix is to probably update the required permissions, but we should test it out first.

**Comment by bluekeyes** [comment]
It seems the transitive nature of GraphQL (you can request nested resources) means we actually need read access to repository contents to get details about commits in the timeline. Adding this permission in our staging environment fixed the problem with private repositories.

I'll update permissions for our production deployments and mark this in the README.
