### ISSUE TITLE
Add var ENV PORT for run in Cloud serverless

### ISSUE THREAD

**Issue by jniltinho** [palantir/policy-bot#475]
Add var ENV PORT + POLICYBOT_PORT

export PORT=8080 or POLICYBOT_PORT=8080

Run on Cloud requer default var $PORT in env serverless
Or add flags --port in command line

**Comment by jniltinho** [comment]
Run:

env POLICYBOT_PORT=$PORT ./policy-bot

**Comment by jniltinho** [comment]
Fix !!

**Comment by bluekeyes** [comment]
Hey @jniltinho, it sounds like you found a solution for this by setting `POLICYBOT_PORT`. If that still doesn't work, or you need to use exactly the `PORT` variable, we may be able to implement something like https://github.com/palantir/bulldozer/pull/229 in Policy Bot.
