### ISSUE TITLE
Re-add SSH signature support

### ISSUE THREAD

**Issue by bluekeyes** [palantir/policy-bot#508]
Support for SSH signatures was added in #504 and reverted in #507. The required `SshSignature` GraphQL type is only available in GitHub.com and GitHub Enterprise 3.7 and newer. On GHE 3.6 (what we're currently running internally), all evaluations fail with this error:

```
failed to compute approval status: failed to list commits: failed to load commits: No such type SshSignature, so it can't be a fragment condition
```

I reverted the feature to unblock other fixes, but we should add it again if either:

1. We also add feature detection so that it is only enabled when GitHub supports it
2. We upgrade to GHE 3.7 internally and are ready to drop support for older versions in Policy Bot

**Comment by dadicool** [comment]
hi @bluekeyes, has the upgrade to GHE 3.7 been done on your side? Any potential timeline for reintegrating https://github.com/palantir/policy-bot/pull/504 at some point?

**Comment by bluekeyes** [comment]
We're actively working on the GHE 3.7 upgrade and have tentatively scheduled our upgrade for next week, although that may be delayed. It's taken a while because there's a required database migration that is prohibitively slow with our data (fails after 8 hours), so we've been working with GitHub Support to resolve that.

Once we upgrade, it should be safe to add this again and drop support for GHE 3.6.

**Comment by dadicool** [comment]
Thanks for pushing this through

**Comment by knechtionscoding** [comment]
@bluekeyes I'd love to use policy-bot, but we are running GH Enterprise 3.6.3 and haven't upgraded yet. Is there a way to disable the sshSignatures specifically so we can use Policy-bot? I know 3.6x is a little older, but it is still supported by Github and having releases made for it still.

**Comment by asvoboda** [comment]
3.6.x went out of support a few days ago https://docs.github.com/enterprise-server@3.6/admin/release-notes
```
This version of GitHub Enterprise was discontinued on 2023-08-16. No patch releases will be made, even for critical security issues. For better performance, improved security, and new features, [upgrade to the latest version of GitHub Enterprise](https://docs.github.com/enterprise/admin/guides/installation/upgrading-github-enterprise/). For help with the upgrade, [contact GitHub Enterprise support](https://enterprise.github.com/support).
```

**Comment by bluekeyes** [comment]
Until you upgrade GHE, you can also try running Policy Bot 1.28.0, as this is the last release that supports GHE versions older than 3.7. The changes in the releases since then are either minor or for GitHub.com, so you shouldn't miss much functionality.

**Comment by knechtionscoding** [comment]
Thank you!
