### ISSUE TITLE
Setting POLICYBOT_LOG_LEVEL doesn't work

### ISSUE THREAD

**Issue by DavidHe1127** [palantir/policy-bot#522]
Set `POLICYBOT_LOG_LEVEL` env var doesn't work e.g setting it to `warn` still produces `info` level logs.

**Comment by bluekeyes** [comment]
Good catch, looks like we never actually implemented the logging variables. Should be fixed by #523.

**Comment by bluekeyes** [comment]
If you'd like to test this out before the next release, you can try using the `latest` Docker tag, e.g. `docker pull palantirtechnologies/policy-bot:latest`

**Comment by DavidHe1127** [comment]
@bluekeyes thanks for fixing this up. Much appreciated
