### ISSUE TITLE
Restrict approvals from the PR contributors even if contributor is not the owner of the PR

### ISSUE THREAD

**Issue by atul-tw** [palantir/policy-bot#583]
Currently, if I am a contributor to the PR for which owner is someone is else then with my approval the PR gets approved.

**Comment by bluekeyes** [comment]
By default, Policy Bot does not allow approvals from the author/owner of a PR or from contributors on the PR. There are three options you can set in the policy to control this behavior:

* `allow_author` - if `true`, the author/owner of the PR can approve
* `allow_contributor` - if `true`, the author/owner and any contributors to the PR can approve
* `allow_non_author_contributor` - if `true`, contributors to the PR can approve, but the author/owner cannot approve

These options apply to each rule, so some rules may allow contributor approvals while others do not. Are any of these options set in your policy?

**Comment by atul-tw** [comment]
Oh great... Thanks for providing these inputs...!!!
