### ISSUE TITLE
Prevent search engines from indexing policy bot...

### ISSUE THREAD

**Issue by filipvh** [palantir/policy-bot#586]
Might be a good idea to add an (optional) robots.txt that signals to search engines not to index this webapp.
A noindex tag (meta) in the html might also be a good idea.
Any other ideas?

**Comment by bluekeyes** [comment]
Thanks for the suggestion. To clarify, this is to exclude the landing / home page that describes how to use the bot? The pages with policy details should require authentication and I think would not be indexed.

**Comment by filipvh** [comment]
A friend of mine pointed this out:
![Screenshot_20230613-001712.png](https://github.com/palantir/policy-bot/assets/6095002/949b78bd-5361-4965-9a1b-2d0427e0858d)
