### ISSUE TITLE
Allow '=' as comparison operator

### ISSUE THREAD

**Issue by ghost** [palantir/policy-bot#623]
The `modified_lines` condition allows only `<` or `>`.
I'd like to ask for an exact `=` option too.

The use case is that I want to allow different requirements for changes made by our automation, which should modify exactly two lines in a specific file.

There is no way to specify that accurately enough with `<` and `>`.

Thanks.

**Comment by asvoboda** [comment]
This sounds like a reasonable feature request. We'll happily review the change if you are interested in opening the PR.
