### ISSUE TITLE
Misleading documentation about file path regular expressions

### ISSUE THREAD

**Issue by srabraham** [palantir/policy-bot#624]
The documentation makes it look like path regexps implicitly anchor at the start and end, but I've confirmed for myself that this isn't the case. It'd probably be better to just put "^" and "$" on each of the paths/ignores in the documentation, to avoid confusion for others. For example, `"^server/views/.*\\.tmpl$"` rather than `"server/views/.*\\.tmpl"`.

See screenshot from README.md for context.

<img width="286" alt="image" src="https://github.com/palantir/policy-bot/assets/23407555/9b0ded87-9fdf-48eb-9c17-686694ea8d6a">

**Comment by bluekeyes** [comment]
Good point, this could be confusing. I added explicit anchors in #625.
