### ISSUE TITLE
Support "only_has_contributor_in"

### ISSUE THREAD

**Issue by dsw2127** [palantir/policy-bot#74]
It would be useful to be able to design a policy that only allows PRs that are signed off on by a team by nature of either approving or by being the author/sole contributor. Currently we can create a policy with a top-level OR  of two rules - 1) if has author in desired team, allow approval from broad group 2) allow approval from desired team. However, with this policy if the desired team opens a PR and then someone from outside that team pushes an arbitrary update to the branch, anyone in the broad group can approve, so that update is not signed off on by the desired team.

If we had a "only_has_contributor_in" we could combine that with has_author_in to ensure that edge case cannot happen. Open to other ways of accomplishing this as well!

This is useful for a workflow where the desired team that owns a particular process is small, so it is unfortunate to block those PRs, created by that team, on an approval from another person in that team.

**Comment by bluekeyes** [comment]
After some discussion, I'm leaning towards implementing this as an `author_is_only_contributor` predicate, which is less general, but I think better communicates the intent behind this request. That said, `has_contributor_in` and `only_has_contributor_in` more closely match the other supported predicates.
