### ISSUE TITLE
Create new production Release 🚀 

### ISSUE THREAD

**Issue by TomVanGreevenbroek** [palantir/policy-bot#772]
Hi!

I was wondering if you could create a new release for all the [changes so far](https://github.com/palantir/policy-bot/compare/v1.34.1...develop) 😄 

I'm really eager to use the new functionality introduced in this PR: https://github.com/palantir/policy-bot/pull/752

Many thanks in advance 😃

**Comment by bluekeyes** [comment]
Thanks for the reminder - at the time, it looked like there were several other changes that were going to land soon, so I held off on a release, but when those were delayed I forgot to go back and create one.

[1.35.0](https://github.com/palantir/policy-bot/releases/tag/v1.35.0) is out now with the required conditions feature.
