### ISSUE TITLE
Concurrent deployments can overwrite statuses unintentionally

### ISSUE THREAD

**Issue by iainlane** [palantir/policy-bot#799]
I've just deployed a production installation of the bot alongside the dev one. We'll keep two so that we can validate version updates using test repos before rolling them out to real users.

Almost all good, but I noticed that the prod deployment is overwriting the status from the dev one.

I have the status check contexts set like this

- dev: `policy-bot-dev`
- prod: `policy-bot`

and this code:

https://github.com/palantir/policy-bot/blob/79ce388e099764a523864d00c53b06a602dc7331/server/handler/status.go#L44-L46

means that the prod one acts on dev's statuses, since `policy-bot` is a prefix of e.g. `policy-bot-dev: main`.

Not tried yet, but I imagine it's easy to work around by using `dev-policy-bot` instead. Just thought I'd see if this is something to fix, maybe by checking for a `:` following the context name?

**Comment by bluekeyes** [comment]
Good catch, we've never had two instance of the bot running on the same repository before. Should be fixed by #801.
