### ISSUE TITLE
❓ What does the `expand_required_reviewers` option do?

### ISSUE THREAD

**Issue by marcellino-ornelas** [palantir/policy-bot#860]
## Description

Im trying to figure out what the `expand_required_reviewers` option actually does? Does it post a comment of the require reviews onto the PR? or does it only surface on the UI? If it is a comment, does the comment get updated as rules are completed? Do you have an example/image/etc of what this would look like?

https://github.com/palantir/policy-bot?tab=readme-ov-file#expanding-required-reviewers-

**Comment by bluekeyes** [comment]
Good question, we should probably add some more information to the README. This is a UI-only feature that shows the list of users who are able to approve a specific rule. Here's a redacted screenshot from our internal instance - the blocked names are other users who are allowed to approve:

<img width="567" alt="expanded-reviewers" src="https://github.com/user-attachments/assets/231b0025-90e4-442a-abd8-730808bb5be9">

When you first expand the "Details" section for a rule, it triggers a background request to populate this list of users.

**Comment by marcellino-ornelas** [comment]
ahhh got ya thank you for the explanation and example 🙏🏽 Yes!! more information about this in the read me would be great 🙌🏽
