### ISSUE TITLE
MaxPullRequestFiles limit incorrectly applies to post-transformation file count instead of raw file count from GitHub API

### ISSUE THREAD

**Issue by zzehring** [palantir/policy-bot#870]
## Description

The current implementation of the `MaxPullRequestFiles` limit (set to 3000) is [being applied after file transformations occur](https://github.com/palantir/policy-bot/blob/develop/pull/github.go#L299-L323), rather than [on the raw file count from the GitHub API](https://github.com/palantir/policy-bot/blob/develop/pull/github.go#L280). This creates an artificial constraint that's more restrictive than GitHub's actual API limits.

In the [switch statement in GithubContext's shared files](https://github.com/palantir/policy-bot/blob/develop/pull/github.go#L294-L318), the [renamed case](https://github.com/palantir/policy-bot/blob/develop/pull/github.go#L299) breaks changes with the `rename` status into 2 separate changes (file added and file deleted). After we get this new list, then we compare the list with GitHub's API limit on [List pull requests files endpoint](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#list-pull-requests-files).

## Example

* A PR with 1,700 renamed files would result in 3,400 entries after transformation
* This PR would be rejected due to exceeding the 3000 limit
* However, the original PR is well within GitHub API's capabilities to process

## Proposal

Apply the [check for `MaxPullRequestFiles`](https://github.com/palantir/policy-bot/blob/develop/pull/github.go#L321-L323) to after the [call to List files for pull request](https://github.com/palantir/policy-bot/blob/develop/pull/github.go#L280). Or, perhaps just omit `MaxPullRequestFiles` entirely, as GH API already imposes the limit. 

Although, the API doc mentions: 

> Responses include a maximum of 3000 files. The paginated response returns 30 files per page by default.

This suggests that even if the PR has more than 3000 files changed, the API will only return 3000. We may need to check this file change number a different way than relying on the `List pull requests files` endpoint (since we don't know for sure if the number of files changes is exactly 3000 or 3001 for example). It appears that [the `Get pull request` endpoint returns a `changed_files` field.](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request) So we could leverage that instead of checking in the `List pull request files` endpoint.

**Comment by bluekeyes** [comment]
Good catch, we should find a way to do this before doing the rename transformation. I think we still need to check against the limit because I believe the GitHub API will stop listing files after 3000 without an error, while we want Policy Bot to return an error in this case to avoid approving a PR due to an incomplete evaluation.

**Comment by zzehring** [comment]
>  I think we still need to check against the limit because I believe the GitHub API will stop listing files after 3000 without an error, while we want Policy Bot to return an error in this case to avoid approving a PR due to an incomplete evaluation.

I think we'd be able to query for the number of files changed directly using the aforementioned [Get pull request](https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request) endpoint, as in the response example/schema, there exists a `changed_files` field.

So we'd be able to use that to get the number without enumerating through the list of files changed itself. Then we can know for sure if there's > 3000 files changed.

**Comment by dblinkhorn** [comment]
I think I have a fix for the issue using @zzehring's proposed solution of utilizing the get pull request endpoint to check `changed_files` count. Can I take this issue and put up a PR?

**Comment by bluekeyes** [comment]
@dblinkhorn sure, I'm happy to review a PR for this if you'd like to submit one.

**Comment by bluekeyes** [comment]
Fixed by #875
