### ISSUE TITLE
Put "pending" polices at top of app

### ISSUE THREAD

**Issue by dlisuk** [palantir/policy-bot#93]
When there are many policies defined for a project, it seems they are displayed in order of definition and it can take a long time to figure out which policies need to pass still, could we change the display sorting such that pending polices are at top, then passed, then skipped or similar?

**Comment by bluekeyes** [comment]
This is a good idea, particularly for policies that have a lot of skipped conditions for different file paths. I'm not sure when we'll have time to implement it, but I believe it will be straight forward to change how the policies are ordered during the UI template rendering.
